[versions]
composeBom = "2024.12.01"
activityCompose = "1.10.1"
navigationCompose = "2.8.9"
composeViewmodel = "2.8.7"
constraintlayoutCompose = "1.1.1"
materialNavigation = "1.8.2"
agp = "8.9.1"
kotlin = "2.3.0"
coreKtx = "1.16.0"
lifecycleRuntimeKtx = "2.8.7"
appcompat = "1.7.0"
kotlinxSerializationJson = "1.8.0"
coil = "2.5.0"
gson = "2.10.1"
kotlinx-collections-immutable = "0.3.7"
retrofitBom = "2.11.0"
okhttp = "4.12.0"
kotlinx-coroutines = "1.8.0"
hilt = "2.56.2"
hiltCompiler = "2.56.2"
hiltNavigationCompose = "1.2.0"
datastorePreference = "1.0.0"
playServicesTime = "16.0.1"
jetbrainsKotlinJvm = "2.0.21"
detekt="1.23.5"
paging = "3.3.6"
camera-core = "1.4.2"
barcode-scanning = "17.3.0"
accompanist-permissions = "0.37.3"
googleServices = "4.4.3"
firebase-bom = "33.3.0"
room = "2.8.1"
hms-base = "6.12.0.300"
hms-push = "6.12.0.300"
playServicesBase = "18.5.0"
webKit = "1.14.0"
auth0-javaJwt = "4.5.0"
auth0-jwksRsa = "0.23.0"
javaxInject = "1"
newRelicVersion = "7.6.12"
msal = "5.0.0"
openTelemetry = "1.18.0"
config-compileSdk = "35"
config-minSdk = "24"
config-targetSdk = "35"
config-versionCode = "1"
junit = "4.13.2"
junitVersion = "1.3.0"
kotlinx-coroutines-test = "1.10.2"
mockk = "1.14.6"
turbine = "1.2.1"

[libraries]
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose"}
androidx-compose-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "composeViewmodel" }
androidx-compose-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintlayoutCompose" }
androidx-material-navigation = { group = "androidx.compose.material", name = "material-navigation", version.ref = "materialNavigation" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-webkit = { group = "androidx.webkit", name = "webkit", version.ref = "webKit" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson"}
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
retrofit-bom = { group = "com.squareup.retrofit2", name = "retrofit-bom", version.ref = "retrofitBom"}
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit" }
retrofit-converter-kotlinSerialization = { group = "com.squareup.retrofit2", name = "converter-kotlinx-serialization" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hiltCompiler" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-datastore-preference = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastorePreference" }
play-services-time = { module = "com.google.android.gms:play-services-time", version.ref = "playServicesTime" }
detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }
paging-runtime = { group = "androidx.paging", name = "paging-runtime", version.ref = "paging" }
paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "paging" }
androidx-camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "camera-core" }
androidx-camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "camera-core" }
androidx-camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "camera-core" }
androidx-camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "camera-core" }
google-mlkit-barcodeScanning = { module = "com.google.mlkit:barcode-scanning", version.ref = "barcode-scanning" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist-permissions" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
huawei-hms-push = { module = "com.huawei.hms:push", version.ref = "hms-push" }
huawei-hms-base = { module = "com.huawei.hms:base", version.ref = "hms-base" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }
play-services-base = { module = "com.google.android.gms:play-services-base", version.ref = "playServicesBase" }
auth0-javaJwt = { group = "com.auth0", name = "java-jwt", version.ref = "auth0-javaJwt" }
auth0-jwksRsa = { group = "com.auth0", name = "jwks-rsa", version.ref = "auth0-jwksRsa" }
javaxInject = { group = "javax.inject", name = "javax.inject", version.ref = "javaxInject" }
newrelic-android-agent = { module = "com.newrelic.agent.android:android-agent", version.ref = "newRelicVersion" }
microsoft-identity-client-msal = { group = "com.microsoft.identity.client", name = "msal", version.ref = "msal" }
io-opentelemetry = { group = "io.opentelemetry", name = "opentelemetry-api", version.ref = "openTelemetry" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-test" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin"}
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
newrelic-agent-android = { id = "com.newrelic.agent.android", version.ref = "newRelicVersion"}
