on:
  workflow_dispatch:

permissions:
  contents: write
  
name: Android Production

jobs:
  android:
    uses: organization-desa/android-cicd-template/.github/workflows/android-production-template.yml@main
    if: startsWith(github.ref, 'refs/heads/release/')
    with:
      java_version: "17"
    secrets:
      RELEASE_KEYSTORE_BASE64: ${{ secrets.RELEASE_KEYSTORE_BASE64 }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS_RELEASE: ${{ secrets.KEY_ALIAS_RELEASE }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}