name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  android:
    uses: organization-desa/android-cicd-template/.github/workflows/android-ci-template.yml@main
    with:
      java_version: "17"
    secrets:
      DEBUG_KEYSTORE_BASE64: ${{ secrets.DEBUG_KEYSTORE_BASE64 }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS_DEBUG: ${{ secrets.KEY_ALIAS_DEBUG }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      
      
